### PR TITLE
add alp3246 tests

### PR DESCRIPTION
**Pull request by alp3246**

### CODE REVIEW

**Comment by kristinedomingo** [comment]
From the project spec, acceptance test files should be between 50-100 lines. Can you add more tests before we merge this in? Thanks!

**Comment by alp3246** [comment]
Yah no problem

**Comment by kristinedomingo** [comment]
One more thing - line 60 in your RunCollatz.in is an invalid test, since the HackerRank problem spec says test cases are >=1 and <= 5,000,000 (the number you have on line 60 is 50,000,000)

**Comment by kristinedomingo** [comment]
And one more on line 50, actually!

**Comment by kristinedomingo** [comment]
And also on line 32... in the future I definitely recommend having some sort of check in your code for input validity (since other people might be using your tests to test their code)

**Pull request merged**
